server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:

mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
    - classpath*:com/**/mapper/*.xml